# Generated by Django 5.1.1 on 2024-09-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cacau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('cacauCategory', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
