# Generated by Django 5.1.1 on 2024-09-27 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('estadoCivil', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('latitude', models.IntegerField(blank=True, default=404)),
                ('longitude', models.IntegerField(blank=True, default=404)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCacau', models.CharField(max_length=45)),
                ('mtdSecagem', models.CharField(max_length=45)),
                ('armazenamento', models.CharField(max_length=45)),
                ('tempoEstoque', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arroba', models.CharField(max_length=45)),
                ('ano', models.CharField(max_length=45)),
                ('trimestre', models.CharField(max_length=45)),
                ('sistemaProd', models.CharField(max_length=45)),
                ('variedadeCultivada', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Fermentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.CharField(max_length=45)),
                ('loteFerm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cacau.lote')),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='loteProd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cacau.producao'),
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assisTec', models.CharField(max_length=45)),
                ('entidadeAssoc', models.CharField(max_length=45)),
                ('cadastroProd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cacau.cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Comercializacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoVenda', models.CharField(max_length=45)),
                ('tipoProd', models.CharField(max_length=45)),
                ('prodCom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cacau.produtor')),
            ],
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('arTotal', models.CharField(max_length=45)),
                ('arPreserv', models.CharField(max_length=45)),
                ('arCultivadaCacau', models.CharField(max_length=45)),
                ('arCultivaVeget', models.CharField(max_length=45)),
                ('areaRecuperada', models.CharField(max_length=45)),
                ('internet', models.PositiveSmallIntegerField()),
                ('desmatamento', models.PositiveSmallIntegerField()),
                ('degradacao', models.PositiveSmallIntegerField()),
                ('endProp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cacau.endereco')),
            ],
        ),
        migrations.AddField(
            model_name='producao',
            name='propProducao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cacau.propriedade'),
        ),
    ]
