# Generated by Django 5.1.1 on 2024-10-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacau', '0003_produtor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtor',
            name='email',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(default=-3, max_length=254),
            preserve_default=False,
        ),
    ]
